version: "3"
services:
  prototypekit-credit-risk:
    build:
      context: .
    image: prototypekit-credit-risk
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev
